version: '3.1'

services:
  nginx:
    image: nginx:alpine
    tty: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        deployer.port: 80
        deployer.domain: nginx.example.com
 
